apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-backend
  labels:
    app: retail-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: retail-backend

  template:
    metadata:
      labels:
        app: retail-backend

    spec:
      containers:
        - name: retail-backend
          image: your-docker-image:latest
          ports:
            - containerPort: 8080

          # optional (only if you use env vars)
          env:
            - name: ENV
              value: "dev"
