apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-health-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/gitops-platform
    targetRevision: HEAD
    path: apps/smart-health/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
